### ISSUE TITLE
Geoprozessierung mit Python | Lektion 6

### ISSUE THREAD

**Issue by Polytrauma83** [UNIGIS-Salzburg/UNIGIS_issue_tracker#10]
**Describe the issue**
Die GUI in ArcGIS Pro (Version 2.9.2) zum Einbinden eines Scripts in eine Toolbox entspricht nicht mehr der in den Unterlagen aufgezeigten Variante. Es wird nicht mehr nur der Pfad zu einem Script angegeben, sondern es gibt nun dafür einen eigenen Reiter "Execution". Relative Pfadnamen können nicht mehr per Checkbox ausgewählt werden. Das Öffnen von kompilierten Dateien mit der Endung *.pyc ist, zumindest so wie in den Unterlagen aufgezeigt (?), nicht möglich (nur *py und *.R).

**Where is the issue located?**
Es handelt sich um die Übung 6.9 und 6.10

**Screenshots**
Früher:
![grafik](https://user-images.githubusercontent.com/65279234/159115672-d0e57ce8-3176-4385-a465-f67b3a459598.png)

Jetzt:
![grafik](https://user-images.githubusercontent.com/65279234/159115644-a59f60dd-9961-4926-9203-915921b0e38a.png)

![grafik](https://user-images.githubusercontent.com/65279234/159115722-5cc06d05-3274-47d9-9563-1247131cc22d.png)

**Comment by petraGIS** [comment]
vielen Dank für den Report! 
Übung 6a wurde angepasst, Übung 6b wurde rausgenommen, da - wie du sagst - es nicht mehr möglich ist, kompilierte Python-Scripts einzubetten. 
Ich werde die anderen StudentInnen über die Änderungen informieren. 
Liebe Grüße, 
Petra
