### ISSUE TITLE
Optional Module: Basics of Application Development - Lesson 3 - Variable declaration in JS

### ISSUE THREAD

**Issue by winnewoerp** [UNIGIS-Salzburg/UNIGIS_issue_tracker#11]
**Description of the issue**
Although there is an [external StackOverfow link](https://stackoverflow.com/questions/762011/whats-the-difference-between-using-let-and-var/11444416) providing further information on the main differences between `var` an `let` keywords in JS, IMHO it should be mentioned directly in the lesson that variable redeclaration is not possible in JS when the `let` keyword is used. This is due to the example given which throws an error when run exactly like stated in the lesson:

```
let firstName = "Julio";
console.log(firstName);

let firstName = "Anna";
console.log(firstName);
```

**Location of the issue**
Optional Module: Basics of Application Development - Lesson 3 - 3.4.2 Variables - 3.4.2.1 Comparison with other Programming Languages
https://elearn.unigis.ac.at/pluginfile.php/8689/mod_resource/content/1/lesson3.html#comparison-with-other-programming-languages

**Comment by moosetraveller** [comment]
Thank you for pointing this out! I agree this example is quite unfortunate. I updated the script slightly which will be available with the next intake.
