### ISSUE TITLE
 Optional Module: Basics of Application Development - Lesson 3: Introdction to Python > 3.4.5.2.3 Paths: Wrong output of print() in example

### ISSUE THREAD

**Issue by winnewoerp** [UNIGIS-Salzburg/UNIGIS_issue_tracker#12]
**Describe the issue**
This

```
c:    temp
norway
c:\temp\norway
c:\temp\norway
```

should be corrected like this

```
c:    emp
orway
c:\temp\norway
c:\temp\norway
```

Both characters of escape sequences are not included in the output. [See here](https://www.online-python.com/wrxi3h1FT9).

**Where is the issue located?**
[Lesson 3: Introdction to Python > 3.4.5.2.3 Paths](https://elearn.unigis.ac.at/pluginfile.php/8689/mod_resource/content/1/lesson3.html#paths)

**Comment by moosetraveller** [comment]
@winnewoerp 
Thank you for pointing this out. I really appreciate it. This is almost a bit of an embarrassing mistake. ;)
I corrected the script. However, because how the internal publishing workflow process works, it won't be updated on the learning platform until next intake.
