### ISSUE TITLE
Optional Module "Application Development using JavaScript": 4.1.2.1 - Python script --> HTML file

### ISSUE THREAD

**Issue by winnewoerp** [UNIGIS-Salzburg/UNIGIS_issue_tracker#13]
**Describe the issue**
It says (probably taken from the _Basics of Application Development_ module):

> Let’s create a new Python script with the name `hello.html`.

It should be:

> Let’s create a new HTML file with the name `hello.html`.

**Where is the issue located?**
Lesson 4 Debugging, section 4.1.2.1, paragraph before HTML snippet
https://elearn.unigis.ac.at/pluginfile.php/8871/mod_resource/content/1/debugging.html#create-a-project

**Comment by moosetraveller** [comment]
Thank you. Will be updated with the next intake.
