### ISSUE TITLE
Optional Module "Application Development using JavaScript": 1.3.2.1 firstName --> lastName

### ISSUE THREAD

**Issue by winnewoerp** [UNIGIS-Salzburg/UNIGIS_issue_tracker#14]
**Describe the issue**
5th line of code example

`let fullName = firstName + ' ' + firstName;`

should be:

`let fullName = firstName + ' ' + lastName;`

**Where is the issue located?**
Lesson 1, section 1.3.2.1 String Concatenation, 5th line of code example
https://elearn.unigis.ac.at/pluginfile.php/8871/mod_resource/content/1/index.html#string-concatenation

**Comment by moosetraveller** [comment]
Thank you. Will be updated with the next intake.
