### ISSUE TITLE
Optional Module "Application Development using JavaScript": 1.5 hasRecord --> hasRecords

### ISSUE THREAD

**Issue by winnewoerp** [UNIGIS-Salzburg/UNIGIS_issue_tracker#15]
**Describe the issue**
3rd line of 2nd code example:

Is:

`if (hasRecord) {`

Should be:

`if (hasRecords) {`

**Where is the issue located?**
Lesson 1, section 1.5 Control Structures, 2nd code example
https://elearn.unigis.ac.at/pluginfile.php/8871/mod_resource/content/1/index.html#control-structures
https://elearn.unigis.ac.at/pluginfile.php/8871/mod_resource/content/1/index.html#cb27

**Comment by moosetraveller** [comment]
Thank you. Will be updated with the next intake.
