### ISSUE TITLE
Optional Module "Application Development using JavaScript": 1.7.1 sum += i ?

### ISSUE THREAD

**Issue by winnewoerp** [UNIGIS-Salzburg/UNIGIS_issue_tracker#16]
**Describe the issue**
Sample solution exercise 1.8

`sum = sum + i;`

Why not like this?

`sum += i;`

Wouldn't it be good to introduce this short notation along with iterations?

**Where is the issue located?**
Lesson 1, section 1.7.1
https://elearn.unigis.ac.at/pluginfile.php/8871/mod_resource/content/1/index.html#for-loop
https://elearn.unigis.ac.at/pluginfile.php/8871/mod_resource/content/1/index.html#cb36

**Comment by moosetraveller** [comment]
I purposely did not introduce the short-hand in this introductory module. Explicit is better readable than implicit.

See the The Zen of Python:
> Explicit is better than implicit.

https://peps.python.org/pep-0020/

Following article describes well why:

>The aphorism speaks for itself. It means that it is better to make the code more verbose and explicit. Doing this will make the code readable. Hiding code functionality might have repercussions as other programs might not be able to understand the code.

https://towardsdatascience.com/the-zen-of-python-a-guide-to-pythons-design-principles-93f3f76d088a

Especially for beginners, the explicit variant is better understandable.

However, I appreciate the suggestion. I may add a note to the script. Also, thank you very much for all other input to make the script better!!

**Comment by moosetraveller** [comment]
I just realize that you reported this for the JavaScript module. However, I personally think that this aphorism should be applied to any programming language. Code should be written for the reader (unless you need a high-performance application, optimize an algorithm, or every millisecond counts). I am a huge advocate of clean and readable code.

I think it's better to learn the explicit way first. At the end it comes down to preference. :)
