### ISSUE TITLE
Optional Module "Application Development using JavaScript": 1.9 - Number.toFixed() returns a string

### ISSUE THREAD

**Issue by winnewoerp** [UNIGIS-Salzburg/UNIGIS_issue_tracker#18]
**Describe the issue**
IMHO it would be worth mentioning that `Number.toFixed()` transforms the number into a string or link a resource that mentions this. Maybe also mention `parseFloat()`. Only one parsing function (`parseInt()`) is mentioned in the lesson before (within an exercise).

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed

**Where is the issue located?**
Lesson 1, section 1.9 Standard Built-In Objects and Functions
https://elearn.unigis.ac.at/pluginfile.php/8871/mod_resource/content/1/index.html#standard-built-in-objects-and-functions

**Comment by moosetraveller** [comment]
I added a note for `parseFloat()`. Thank you.
