### ISSUE TITLE
1.3 Exercise: environmental monitoring across scales

### ISSUE THREAD

**Issue by pfatscs** [UNIGIS-Salzburg/UNIGIS_issue_tracker#4]
1.3 Exercise: environmental monitoring across scales
The link to "British Columbia - Environmental Reporting" doesn't work, the access is denied.

**Comment by gwallentin** [comment]
Sorry, for the late reaction. I've missed that one (will not happen anymore, I've now set an automatic issue notification). The link is fixed now and will be available for the next intake. Thanks for reporting.
