### ISSUE TITLE
Module Application Development JavaScript - Chapter 5/Assignment 2 File not found

### ISSUE THREAD

**Issue by rschiffer** [UNIGIS-Salzburg/UNIGIS_issue_tracker#5]
File mapquest_solution.html cannot be found for download. 

This file should be provided in chapter 5 _Requesting Data with Ajax_ and is needed as basis for Assignment 2 _Geocoding Functions_.

![ADJS_Chapter_5_File_not_found](https://user-images.githubusercontent.com/51607747/59415529-f03a4300-8dc3-11e9-8194-db5eb6ff7115.png)

**Comment by gwallentin** [comment]
Thanks for reporting this issue. The broken link is fixed now.
