### ISSUE TITLE
Not able to download PDF of module materiel for Module Visualisation and Cartography

### ISSUE THREAD

**Issue by widpra** [UNIGIS-Salzburg/UNIGIS_issue_tracker#6]
While i was trying to download pdf version the module material for module visualisation and cartography, i wasn't able to download the file and i kept getting file not found error. I am able to download the epub version. It seens the issue exist for pdf version only

![image](https://user-images.githubusercontent.com/12053486/77245538-5acbb980-6c47-11ea-8456-ec4c909317c4.png)

**Comment by gwallentin** [comment]
The error is fixed now. Thanks for reporting the issue!
