### ISSUE TITLE
Module Geographical Analysis -  3.3.3 Exercise

### ISSUE THREAD

**Issue by bovandersteene** [UNIGIS-Salzburg/UNIGIS_issue_tracker#8]
**Describe the issue**
The extend values are wrong in 3.3.3 Exercise: Allocation.
As mentioned in the text: **The extent of the study area is like before:** but the values displayed here are different.
The extended values should be:
```
Top: 5660000
Right: 780000
Bottom: 5375000
Left: 290000
```

**Where is the issue located?**
3.3.3 Exercise: Allocation

**Screenshots**
<img width="398" alt="Screen Shot 2021-11-04 at 11 10 14" src="https://user-images.githubusercontent.com/1673799/140295850-2409ce3a-31b5-4b09-94c3-61891275ad4a.png">

**Further information**
Provide any further information that may help to find and solve the issue.

**Comment by karnassioti** [comment]
corrected the values in the exercise
