### ISSUE TITLE
6.7.1 GeoPy

### ISSUE THREAD

**Issue by erichstoeckli** [UNIGIS-Salzburg/UNIGIS_issue_tracker#9]
In the example in chapter "6.7.1 GeoPy" a small error has slipped in:

_print(**result**.point)  # outputs: Point(47.78824, 13.06035, 0.0)_
should be replaced py
_print(**location**.point)  # outputs: Point(47.78824, 13.06035, 0.0)_

**Comment by moosetraveller** [comment]
Thank you @erichstoeckli for bringing that to my attention.
I will correct the error and inform the other students.
